# Generated by Django 2.1.8 on 2019-04-28 10:47

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=100000)),
                ('example_in', models.TextField(max_length=1000)),
                ('example_out', models.TextField(max_length=1000)),
                ('time_limit', models.PositiveSmallIntegerField(validators=[mainApp.models.isValidTimeLimit])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
