# Generated by Django 2.1.8 on 2019-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20190428_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='problempost',
            name='input_explain',
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name='problempost',
            name='output_explain',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
