# Generated by Django 2.1.8 on 2019-05-02 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0003_auto_20190428_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=100000)),
                ('result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('-', 'Wait')], max_length=1)),
                ('problem_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ProblemPost')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
