# Generated by Django 2.1.8 on 2019-05-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_solvepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvepost',
            name='lang',
            field=models.PositiveSmallIntegerField(choices=[(1, 'python3')], default=1),
            preserve_default=False,
        ),
    ]
