# Generated by Django 2.1.8 on 2019-05-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_solvepost_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvepost',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pass'), (2, 'Fail'), (3, 'Wait')]),
        ),
    ]
