# Generated by Django 2.1.8 on 2019-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20190503_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvepost',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pass'), (2, 'Fail'), (3, 'Wait')], default=3),
        ),
    ]
