# Generated by Django 2.1.8 on 2019-05-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20190503_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvepost',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
