# Generated by Django 2.1.8 on 2019-05-04 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_solvepost_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvepost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
