# Generated by Django 2.1.8 on 2019-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_solvepost_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvepost',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
