# Generated by Django 2.1.8 on 2019-05-06 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_solvepost_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempost',
            name='time_limit',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
