# Generated by Django 2.1.8 on 2019-05-06 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20190506_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempost',
            name='time_limit',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
