# Generated by Django 2.1.8 on 2019-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20190506_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='problempost',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
