# Generated by Django 2.1.8 on 2019-05-08 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_problempost_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='problempost',
            name='code_limit',
            field=models.PositiveSmallIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='problempost',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
